language: node_js
node_js:
  - "5.1.0"
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -d postgres -a -f ./PostgreSQL/createUser.sql
  - export PGPASSWORD="admin"
  - psql -U sharedserver_user -d postgres -a -f ./PostgreSQL/database.sql
  - psql -U sharedserver_user -d sharedserver -a -f ./PostgreSQL/tables.sql
  - psql -U sharedserver_user -d sharedserver -a -f ./PostgreSQL/storedProcedures.sql
  - psql -U sharedserver_user -d sharedserver -a -f ./PostgreSQL/defaultDatabase.sql
script: "npm run-script coverage"
deploy:
  provider: heroku
  api_key: f743ba73-0c46-4dbc-8318-b3eca095d5f5
  app: tp-7552-g05-sharedserver
